add version intelligence to NSA-proof SSH

diff --git a/modules/ssh b/modules/ssh
--- a/modules/ssh
+++ b/modules/ssh
@@ -1,48 +1,83 @@
-#!/bin/sh
+#!/bin/bash
 #
 # try to secure OpenSSH... a bit
 #
 # comotion@krutt.org
 
+sshver=$(sshd -V 2>&1 | grep -v unknown | head -n 1) 
+case $sshver in
+    OpenSSH_*)
+        v=$(echo $sshver | cut -f 2 -d_ | cut -f 1 -d ' ')
+        ;;
+    *)
+        v=UNKNOWN
+esac
+
+if [ "$v" = "UNKNOWN" ]
+then
+    echo "this script currently only supports OpenSSH. Email $sshver to comotion@krutt.org and we shall work it in" 1>&2
+    exit 1
+fi
+
+
+cd /etc/ssh
+cp sshd_config sshd_config.$$
+
+# these are mostly supported
 sed -i \
 -e 's/PermitRootLogin *yes.*/PermitRootLogin no/' \
 -e 's/UsePrivilegeSeparation *no.*/UsePrivilegeSeparation yes/' \
 -e 's/StrictModes *no.*/StrictModes yes/' \
 -e 's/IgnoreRhosts *no.*/IgnoreRhosts yes/' \
 -e 's/PermitEmptyPasswords *yes.*/PermitEmptyPasswords no/' \
-/etc/ssh/sshd_config
+-e 's/^\(HostKey .*ssh_host_dsa_key\)/#\1/' \
+sshd_config
 
 # should be this but curve25519 is not supported everywhere
-#kex='KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256'
+kexup='curve25519-sha256@libssh.org'
 
-kex='KexAlgorithms diffie-hellman-group-exchange-sha256'
+kex='diffie-hellman-group-exchange-sha256'
 
-ciphers='Ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
+ciphers='aes256-ctr,aes192-ctr,aes128-ctr'
+ciphersup='aes256-gcm@openssh.com,aes128-gcm@openssh.com,chacha20-poly1305@openssh.com'
+macs='hmac-sha2-512,hmac-sha2-256,hmac-ripemd160'
+macsup='hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com'
 
-macs='MACs hmac-sha2-512,hmac-sha2-256,hmac-ripemd160'
 
 
-if grep -q ^KexAlgorithms /etc/ssh/sshd_config
+if [[ "$v" < "5.9" ]]
 then
-   sed -i "s/^KexAlgorithms/$kex/" /etc/ssh/sshd_config
-else
-    echo "$kex" >> /etc/ssh/sshd_config
-fi
-if grep -q ^Ciphers /etc/ssh/sshd_config
+    echo "shitty old SSH $v detected, please upgrade!"
+elif [[ "$v" > "6.0" ]]
 then
-   sed -i "s/^Ciphers/$ciphers/" /etc/ssh/sshd_config
-else
-    echo "$ciphers" >> /etc/ssh/sshd_config
+    ciphers="$ciphersup,$ciphers"
+    macs="$macsup"
+    kex="$kexup,$kex"
 fi
-if grep -q ^MACs /etc/ssh/sshd_config
-then
-   sed -i "s/^MACs/$macs/" /etc/ssh/sshd_config
-else
-    echo "$macs" >> /etc/ssh/sshd_config
-fi
+
+
 
 cd /etc/ssh
-mkdir broken
+if grep -q ^KexAlgorithms sshd_config
+then
+   sed -i "s/^KexAlgorithms .*/KexAlgorithms $kex/" sshd_config
+else
+    echo "$kex" >> sshd_config
+fi
+if grep -q ^Ciphers sshd_config
+then
+   sed -i "s/^Ciphers .*/Ciphers $ciphers/" sshd_config
+else
+    echo "$ciphers" >> sshd_config
+fi
+if grep -q ^MACs sshd_config
+then
+   sed -i "s/^MACs .*/MACs $macs/" sshd_config
+else
+    echo "$macs" >> sshd_config
+fi
+
+mkdir -p broken
 mv ssh_host_dsa_key* ssh_host_ecdsa_key* ssh_host_key* broken
 # create broken links to force SSH not to regenerate broken keys
 ln -s ssh_host_ecdsa_key ssh_host_ecdsa_key
@@ -52,11 +87,17 @@ ln -s ssh_host_key ssh_host_key
 # remove weak moduli
 [ -f broken/moduli ] || cp moduli broken
 awk '{ if ($5 > 2048){ print } }' moduli > /tmp/moduli
-mv /tmp/moduli /etc/ssh/moduli
+mv /tmp/moduli moduli
 
-/etc/init.d/ssh reload
-
-echo "Please TEST your SSHD by making a new connection BEFORE disconnecting!" >&2
+if ! sshd -t
+then
+    echo "SSHD config failed, reverting to untouched one. Please investigate sshd_config.$$.new"
+    cp sshd_config sshd_config.$$.new
+    mv sshd_config.$$ sshd_config
+else
+    /etc/init.d/ssh reload
+    echo "SSH reloaded. Please TEST your SSHD by making a new connection BEFORE disconnecting this session!" >&2
+fi
 
 # controversial options:
 # X11Forwarding
